version: "3.8"

services:
  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./auth_service/.env
    networks:
      - aarvasa-net

  chatbot-service:
    build:
      context: ./chatbot_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot_service/.env
    networks:
      - aarvasa-net

networks:
  aarvasa-net:
    driver: bridge
